<?php
declare(strict_types=1);
require_once __DIR__ . '/../config/database.php';
$columns = tableColumns(); $primary = primaryColumn($columns); $key = $primary['COLUMN_NAME']; $id = (string) ($_GET['id'] ?? $_POST['id'] ?? '');
$statement = db()->prepare('SELECT * FROM ' . identifier('instrumentos2') . ' WHERE ' . identifier($key) . ' = :id'); $statement->execute(['id' => $id]); $row = $statement->fetch();
if (!$row) { header('Location: index.php?mensaje=' . urlencode('Instrumento no encontrado.')); exit; }
$editable = array_values(array_filter($columns, static fn (array $column): bool => $column['COLUMN_NAME'] !== $key && $column['EXTRA'] !== 'auto_increment')); $error = null;
if ($_SERVER['REQUEST_METHOD'] === 'POST') { foreach ($editable as $column) { $name = $column['COLUMN_NAME']; $row[$name] = trim((string) ($_POST[$name] ?? '')); } $required = array_filter($editable, static fn (array $column): bool => $column['IS_NULLABLE'] === 'NO' && $column['COLUMN_DEFAULT'] === null); if (array_filter($required, static fn (array $column): bool => $row[$column['COLUMN_NAME']] === '')) { $error = 'Completa todos los campos obligatorios.'; } else { try { $sets = array_map(static fn (array $column): string => identifier($column['COLUMN_NAME']) . ' = :' . $column['COLUMN_NAME'], $editable); $statement = db()->prepare('UPDATE ' . identifier('instrumentos2') . ' SET ' . implode(', ', $sets) . ' WHERE ' . identifier($key) . ' = :primary_id'); foreach ($editable as $column) { $name = $column['COLUMN_NAME']; $statement->bindValue(':' . $name, $row[$name] === '' ? null : $row[$name]); } $statement->bindValue(':primary_id', $id); $statement->execute(); header('Location: index.php?mensaje=' . urlencode('Instrumento actualizado correctamente.')); exit; } catch (Throwable $exception) { $error = 'No se pudo actualizar el instrumento: ' . $exception->getMessage(); } } }
function renderField(array $column, mixed $value): string { $name = $column['COLUMN_NAME']; $required = $column['IS_NULLABLE'] === 'NO' && $column['COLUMN_DEFAULT'] === null; return '<label for="' . e($name) . '">' . e($name) . ($required ? ' *' : '') . '</label><input id="' . e($name) . '" name="' . e($name) . '" type="' . e(inputType($column)) . '" value="' . e($value) . '"' . ($required ? ' required' : '') . '>'; }
?><!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Editar instrumento</title><link rel="stylesheet" href="styles.css"></head><body><main class="shell shell-narrow"><a class="back-link" href="index.php">← Volver a instrumentos</a><section class="form-panel"><p class="eyebrow">Editar registro #<?= e($id) ?></p><h1>Editar instrumento</h1><?php if ($error !== null): ?><div class="alert alert-error"><?= e($error) ?></div><?php endif; ?><form method="post" class="user-form"><input type="hidden" name="id" value="<?= e($id) ?>"><?php foreach ($editable as $column): echo renderField($column, $row[$column['COLUMN_NAME']] ?? ''); endforeach; ?><div class="form-actions"><a class="button" href="index.php">Cancelar</a><button class="button button-primary" type="submit">Guardar cambios</button></div></form></section></main></body></html>